# SPDX-License-Identifier: MIT
# Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.



xusl += files([ 'MpioCfgPointsPhx.c', 'MpioCmn2Phx.c',
                'MpioLibPhx.c', 'MpioPciePhx.c',
                'MpioPortVisibilityPhx.c', 'MpioPhx.c',
                'MpioIp2IpPhx.c', 'MpioTopologyPhx.c',
                'MpioInitPhx.c', 'MpioInitFlowPhx.c' ])
