/* SPDX-License-Identifier: MIT */
/* Copyright (C) 2021 - 2025 Advanced Micro Devices, Inc. All rights reserved. */
/**
 * @file  FchUsbDefaults.c
 * @brief FCH USB Default Settings
 *
 */

#include <SilCommon.h>
#include <FchUsb-api.h>

const FCHUSB_INPUT_BLK mFchUsbDefaults = {
  .DieBusNum = 0,
  .Xhci0Enable = true,
  .Xhci1Enable = true,
  .Xhci2Enable = false,
  .Xhci3Enable = false,
  .XhciECCDedErrRptEn = false,
  .Xhci0DevRemovable = 0,
  .XhciUsb3PortDisable = 0,
  .XhciUsb2PortDisable = 0,
  .XhciOCpinSelect[0].Field = {0xFFFFFFFF, 0xFFFF},
  .XhciOCpinSelect[1].Field = {0xFFFFFFFF, 0xFFFF},
  .XhciOCpinSelect[2].Field = {0xFFFFFFFF, 0xFFFF},
  .XhciOCpinSelect[3].Field = {0xFFFFFFFF, 0xFFFF},
  .XhciOcPolarityCfgLow = false,
  .Usb3PortForceGen1 = 0x0,
  .OemUsbConfigurationTable = 0,
  .UsbInitData = { { 0 }, { 0 }, { 0 }, 0, 0, 0, 0 },
  .UsbSparseModeEnable = true,
  .UsbDbgSCPipeSwitchEnable = false,
  .DdiModeEnable = 0,
  .UsbDbgClkDisable = false,
  .PdInterruptModeEn = 0,
  .Usb4Host[0] = {
    .InitEnable = true,
    .HostEnable = true,
    .Usb3HCDisable = 0,
    .PcieTunnelingDisable = 0,
    .Usb3TunnelingDisable = 0,
    .DPTunnelingDisable = false,
    .Tbt3NotSupport = false,
    .PcieAdpHidden = 0,
    .Usb3AdpHidden = 0,
    .DPAdpHidden = 0,
    .Gen3Disable = false,
    .PhyEnable = 0x1,
    .Gen3Support = 0x1,
    .TxFFEMode = 0x00,
    .TxFFEPreSetValue = 0xFF,
    .ClxEnable = 0,
    .P4PgEnable = 0,
    .LinkSpeed = 1,
    .OnboardRetimer = 0,
    .ZprEnable = false,
    .SSPortDisable = 0x00,
    .Reserved = {0},
  },
  .Usb4Host[1] = {
    .InitEnable = true,
    .HostEnable = true,
    .Usb3HCDisable = 0,
    .PcieTunnelingDisable = 0,
    .Usb3TunnelingDisable = 0,
    .DPTunnelingDisable = false,
    .Tbt3NotSupport = false,
    .PcieAdpHidden = 0,
    .Usb3AdpHidden = 0,
    .DPAdpHidden = 0,
    .Gen3Disable = false,
    .PhyEnable = 0x1,
    .Gen3Support = 0x1,
    .TxFFEMode = 0x00,
    .TxFFEPreSetValue = 0xFF,
    .ClxEnable = 0,
    .P4PgEnable = 0,
    .LinkSpeed = 1,
    .OnboardRetimer = 0,
    .ZprEnable = false,
    .SSPortDisable = 0x00,
    .Reserved = {0},
  },
  .Usb4DebugSCDisable = 0x0000,
  .Usb4PhyTuningEnable = false,
  .Usb4PhyTuningSetPtr = 0,
  .Usb4PhyTuningSetSize = 0,
};
