# SPDX-License-Identifier: MIT
# Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.

incdir += include_directories( '.' )

xusl += files(['MpioTopologyBrh.c', 'MpioLibBrh.c',
               'MpioBrh.c', 'MpioPortVisibilityBrh.c',
               'MpioPcieBrh.c', 'MpioCmn2Brh.c', 'MpioCfgPointsBrh.c',
               'MpioIp2IpBrh.c', 'MpioServerHotplugBrh.c'
              ])
