/* SPDX-License-Identifier: MIT */
/* Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved. */
/**
 * @file  NbioDefaults.h
 * @brief This file contains the Nbio default configurations
 *
 */

#pragma once

#include <Nbio/Brh/include/IoagrReg.h>
#include <Nbio/Brh/include/IoapicReg.h>
#include <Nbio/Brh/include/IohcReg.h>
#include <Nbio/Brh/include/Iommul1Reg.h>
#include <Nbio/Brh/include/SstReg.h>

#define NBIO_PPR_INIT_VALUES_TBL \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF0, \
  SIL_RESERVED_1104, \
  SIL_RESERVED_0899, \
  0x0 << SIL_RESERVED_0900 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF1, \
  SIL_RESERVED_1104, \
  SIL_RESERVED_0899, \
  0x0 << SIL_RESERVED_0900 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF2, \
  SIL_RESERVED_1143, \
  SIL_RESERVED_0899, \
  0x0 << SIL_RESERVED_0900 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF0, \
  SIL_RESERVED_1104, \
  SIL_RESERVED_0895, \
  0x0 << SIL_RESERVED_0896 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF1, \
  SIL_RESERVED_1104, \
  SIL_RESERVED_0895, \
  0x0 << SIL_RESERVED_0896 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF2, \
  SIL_RESERVED_1143, \
  SIL_RESERVED_0895, \
  0x0 << SIL_RESERVED_0896 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF0, \
  SIL_RESERVED_1104, \
  SIL_RESERVED_0903, \
  0x0 << SIL_RESERVED_0904 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF1, \
  SIL_RESERVED_1104, \
  SIL_RESERVED_0903, \
  0x0 << SIL_RESERVED_0904 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF2, \
  SIL_RESERVED_1143, \
  SIL_RESERVED_0903, \
  0x0 << SIL_RESERVED_0904 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF0, \
  SIL_RESERVED_1104, \
  SIL_RESERVED_0893, \
  0x0 << SIL_RESERVED_0894 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF1, \
  SIL_RESERVED_1104, \
  SIL_RESERVED_0893, \
  0x0 << SIL_RESERVED_0894 \
  ), \
        SMN_ENTRY_PROPERTY_RMW(PROPERTY_PRESENT_NBIF2, \
  SIL_RESERVED_1143, \
  SIL_RESERVED_0893, \
  0x0 << SIL_RESERVED_0894 \
  ), \
        SMN_ENTRY_RMW(SIL_RESERVED_1500, \
  SIL_RESERVED_1294, \
  0x1 << SIL_RESERVED_1295 \
  ), \
        SMN_ENTRY_RMW(SIL_RESERVED_1712, \
  SIL_RESERVED_1724, \
  0x1 << SIL_RESERVED_1725 \
  ), \
        SMN_ENTRY_RMW(SIL_RESERVED_1712, \
  SIL_RESERVED_1724, \
  0x1 << SIL_RESERVED_1725 \
  ),
