@echo off
Rem Batch file to generate the customer visible SIL API documentation file(s)
Rem   for use/display on the gh_pages web site.
Rem

Rem Validate that the project control files exist
if not exist "SilApi.dox"     ( Echo "GenPdf: ERROR missing Doxygen config file."       & cd .. & exit /b 1 )

Rem Make sure the build dir is present.
if not exist "build"  (
    mkdir build
) else (
    del /S /Q build\*.*  > nul
)

Rem Use Doxygen to parse the source tree; output to .\build\DoxyScans
echo " ************************************"
echo " Starting Doxygen scan for SilApi project"
doxygen SilApi.dox >> build\DoxyCons.log
if %ERRORLEVEL% NEQ 0 (
    echo "**** Dox: Doxygen generation failed."
    echo "****"
    goto Exit
)
if exist "build/Doxy.log" (
    echo "**** Dox: Warnings or Errors occurred! Check the build/Doxy.log file."
    echo "****"
)
echo " ************************************"
echo "Note The top HTML page generated by Doxygen is placed here: /docs/API-html/"
echo " and is visible here: https://literate-broccoli-67e0cb61.pages.github.io/API-html"

Rem return to the xDocs dir
:Exit
