#!/bin/sh
# Script file to generate the customer visible SIL API documentation file(s)
#   for use/display on the gh_pages web site.
#
#
# Validate that the project control files exist
if [ ! -f SilApi.dox ]    ; then Echo "GenPdf: ERROR missing Doxygen config file." ; exit 1; fi
#
# Make sure the build dir is present.
if [ ! -e build ]
then
    mkdir build
else
    rm -rf build/*
fi
#
# Use Doxygen to parse the source tree; output to ./build/DoxyScans
echo " ************************************"
echo " Starting Doxygen scan for SilApi project"
doxygen SilApi.dox   >> build/DoxyCons.log
if [$? -ne 0]
then
    echo "**** Dox: Doxygen generation failed."
    echo "****"
    exit 1
fi
if [ -e build/Doxy.log ]
then
    echo "**** Dox: Warnings or Errors occurred! Check the build/Doxy.log file."
    echo "****"
fi
echo " ************************************"
echo "Note The top HTML page generated by Doxygen is placed here: /docs/API-html/"
echo " and is visible here: https://literate-broccoli-67e0cb61.pages.github.io/API-html"
