# SPDX-License-Identifier: MIT
# Copyright (C) 2021 - 2025 Advanced Micro Devices, Inc. All rights reserved.

xusl += files([
  'DfAddressTranslationLibBrh.c',
  'RasCmn2Brh.c',
  'RasInitBrh.c',
  'RasIp2IpBrh.c',
  'RasBrh.c',
  'SocLibBrh.c'
  ])

#incdir += include_directories( '.' )
