# SPDX-License-Identifier: MIT
# Copyright (C) 2021 - 2026 Advanced Micro Devices, Inc. All rights reserved.

xusl += files([ 'DfBrh.c', 'BrhBaseFabricTopology.c', 'DfCmn2Brh.c',
                'DfIp2IpBrh.c', 'BrhAbstractRegAcc.c', 'DfInitBrh.c',
                'BrhAcpiLocality.c' ])

#incdir += include_directories( '.' )
