# SPDX-License-Identifier: MIT
# Copyright (C) 2021 - 2025 Advanced Micro Devices, Inc. All rights reserved.


xusl += files([ 'Prom21.c',
                'Prom21Init.c',
                'Prom21Gpio.c',
                'Prom21LoadFw.c',
                'Prom21PreInit.c',
                'Prom21Sata.c',
                'Prom21Xhci.c' ])
