# SPDX-License-Identifier: MIT
# Copyright (C) 2021 - 2025 Advanced Micro Devices, Inc. All rights reserved.



xusl += files([ 'MpioAncDataV1.c', 'MpioCfgPoints.c', 'MpioClassDflts.c',
                'MpioDebugOut.c', 'MpioEarlyTrain.c', 'MpioLib.c',
                'MpioInit.c', 'MpioInitFlow.c', 'MpioMappingResults.c',
                'MpioParser.c', 'MpioPcie.c', 'MpioPortVisibility.c',
                'MpioSupportFunctions.c', 'MpioTopology.c',
                'MpioTrainingResults.c' ])
