# SPDX-License-Identifier: MIT
# Copyright (C) 2021 - 2026 Advanced Micro Devices, Inc. All rights reserved.

xusl += files([ 'DfXBaseFabricTopology.c', 'DfXFabricRegisterAcc.c', 'DfXFabricWdt.c',
                'DfXClkGatingInit.c', 'DfXAcpiDomainInfo.c', 'DfXAcpiTables.c', 'DfXPieRasInit.c',
                'DfX.c' ])

#incdir += include_directories( '.' )

subdir('BRH')
