# SPDX-License-Identifier: MIT
# Copyright (C) 2021 - 2025 Advanced Micro Devices, Inc. All rights reserved.

xusl += files([ 'DfPhx.c', 'DfBaseFabricTopologyPhx.c', 'DfCmn2Phx.c',
                'DfIp2IpPhx.c', 'DfAbstractRegAccPhx.c', 'DfInitPhx.c',
                'DfAcpiDomainInfoPhx.c','DfCsInitPhx.c','DfPeiRasInitPhx.c'])

incdir += include_directories( '.' )
