# SPDX-License-Identifier: MIT
# Copyright (C) 2021 - 2025 Advanced Micro Devices, Inc. All rights reserved.



xusl += files([ 'GfxDisplayPhySettings.c',
                'GfxDisplayTypeSettings.c',
                'GfxEnumConnectorsPhx.c',
                'GfxInfoCollectionPhx.c',
                'GfxInitPhx.c',
                'GfxPhx.c' ])
