# SPDX-License-Identifier: MIT
# Copyright (C) 2021 - 2025 Advanced Micro Devices, Inc. All rights reserved.

xusl += files([
                'NbioPhx.c',
                'NbioBaseInitPhx.c',
                'NbioIoApic.c',
                'NbioIommu.c',
                'NbioPcieComplexDataPhx.c',
                'NbioSmnTable.c',
                'NbioTopMem.c',
                'NbioCmn2RevPhx.c',
                'NbioIp2IpPhx.c',
                'PkgTypeFixups.c' ])

incdir += include_directories( '.' )
incdir += include_directories( 'includePHX' )
