/* SPDX-License-Identifier: MIT */
/* Copyright (C) 2022 - 2025 Advanced Micro Devices, Inc. All rights reserved. */
/**
 * @file  NbioIommuPhxTbl.h
 * @brief This file contains the Nbio Iommu configurations
 *
 */

#pragma once

#include <includePHX/PHX_IOMMUL1.h>
#include <includePHX/PHX_IOMMUL2.h>

// --------------------------------------------------
// IOMMU L1 Initialization
// --------------------------------------------------

  #define NBIO_IOMMU_L1_INIT_TBL \
          SMN_ENTRY_RMW(IOMMUL1x1480009c, \
  L1_FEATURE_CNTRL_EXE_lock_bit_MASK | \
  L1_FEATURE_CNTRL_PMR_lock_bit_MASK, \
  1 << L1_FEATURE_CNTRL_EXE_lock_bit_OFFSET | \
    1 << L1_FEATURE_CNTRL_PMR_lock_bit_OFFSET \
  ), \
          SMN_ENTRY_RMW(IOMMUL1x1470009c, \
  L1_FEATURE_CNTRL_EXE_lock_bit_MASK | \
  L1_FEATURE_CNTRL_PMR_lock_bit_MASK, \
  1 << L1_FEATURE_CNTRL_EXE_lock_bit_OFFSET | \
    1 << L1_FEATURE_CNTRL_PMR_lock_bit_OFFSET \
  ),

// --------------------------------------------------
// IOMMU L2 Initialization
// --------------------------------------------------
  #define NBIO_IOMMU_L2_INIT_TBL \
          SMN_ENTRY_RMW(IOMMUL2x13f01200, \
  L2_ERR_RULE_CONTROL_0_ERRRuleLock0_MASK, \
  0x1 << L2_ERR_RULE_CONTROL_0_ERRRuleLock0_OFFSET \
  ), \
          SMN_ENTRY_RMW(IOMMUL2x157000c0, \
  L2_ERR_RULE_CONTROL_3_ERRRuleLock1_MASK, \
  0x1 << L2_ERR_RULE_CONTROL_3_ERRRuleLock1_OFFSET \
  ), \
          SMN_ENTRY_RMW(IOMMUL2x13f0130c, \
  BITS_6_TO_10_MASK_AAAAASL | \
  BITS_1_TO_5_MASK_AAAAASN, \
  (0x1F << BIT6_OFFSET_AAAAASM) | \
  (0x1F << BIT1_OFFSET_AAAAASO) \
  ),

// --------------------------------------------------
// IOMMU Clock Gating
// --------------------------------------------------
  #define NBIO_IOMMU_CLOCK_GATING_TBL \
          SMN_ENTRY_RMW(IOMMUL2x13f01240, \
  L2_L2B_CK_GATE_CONTROL_CKGateL2BCacheDisable_MASK, \
  (0x1 << L2_L2B_CK_GATE_CONTROL_CKGateL2BCacheDisable_OFFSET) \
  ), \
          SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L1CLKGATING_ENABLED, \
  IOMMUL1x148000cc, \
  L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_MASK | \
  L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_MASK, \
  (0x20 << L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_OFFSET) \
  ), \
          SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L1CLKGATING_ENABLED, \
  IOMMUL1x147000cc, \
  L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_MASK | \
  L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_MASK, \
  (0x20 << L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_OFFSET) \
  ), \
          SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L1CLKGATING_ENABLED, \
  IOMMUL1x149000cc, \
  L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_MASK | \
  L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_MASK, \
  (0x20 << L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_OFFSET) \
  ), \
          SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L1CLKGATING_ENABLED, \
  IOMMUL1x14a000cc, \
  L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_MASK | \
  L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_MASK, \
  (0x20 << L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_OFFSET) \
  ), \
          SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L1CLKGATING_ENABLED, \
  IOMMUL1x18e000cc, \
  L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_MASK | \
  L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_MASK | \
  L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_MASK, \
  (0x20 << L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_OFFSET) | \
  (0x1 << L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_OFFSET) \
  ), \
          SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L2CLKGATING_ENABLED, \
  IOMMUL2x157000cc, \
  L2_L2A_CK_GATE_CONTROL_CKGateL2ARegsDisable_MASK | \
  L2_L2A_CK_GATE_CONTROL_CKGateL2ADynamicDisable_MASK | \
  L2_L2A_CK_GATE_CONTROL_CKGateL2ACacheDisable_MASK, \
  (0x0 << L2_L2A_CK_GATE_CONTROL_CKGateL2ARegsDisable_OFFSET) | \
  (0x0 << L2_L2A_CK_GATE_CONTROL_CKGateL2ADynamicDisable_OFFSET) | \
  (0x0 << L2_L2A_CK_GATE_CONTROL_CKGateL2ACacheDisable_OFFSET) \
  ), \
          SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L2CLKGATING_ENABLED, \
  IOMMUL2x13f01240, \
  L2_L2B_CK_GATE_CONTROL_CKGateL2BRegsDisable_MASK | \
  L2_L2B_CK_GATE_CONTROL_CKGateL2BDynamicDisable_MASK | \
  L2_L2B_CK_GATE_CONTROL_CKGateL2BMiscDisable_MASK | \
  L2_L2B_CK_GATE_CONTROL_CKGateL2BCacheDisable_MASK, \
  (0x0 << L2_L2B_CK_GATE_CONTROL_CKGateL2BRegsDisable_OFFSET) | \
  (0x0 << L2_L2B_CK_GATE_CONTROL_CKGateL2BDynamicDisable_OFFSET) | \
  (0x0 << L2_L2B_CK_GATE_CONTROL_CKGateL2BMiscDisable_OFFSET) | \
  (0x0 << L2_L2B_CK_GATE_CONTROL_CKGateL2BCacheDisable_OFFSET) \
  ),

  #define NBIO_IOMMU_L2_DYNAMIC_POWER_GATING_TBL \
    SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_DYNAMIC_PWRGATING_ENABLED, \
      IOMMUL2x157000f8, \
      0xffffffff, \
      0x800 \
      ), \
    SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_DYNAMIC_PWRGATING_ENABLED, \
      IOMMUL2x15700104, \
      0x1, \
      (0x1 << 0) \
      ), \
    SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_DYNAMIC_PWRGATING_ENABLED, \
      IOMMUL2x157000d4, \
      (0x1 << 4), \
      (0x1 << 4) \
      ), \
    SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_DYNAMIC_PWRGATING_ENABLED, \
      IOMMUL2x13f01254, \
      (0x1 << 4), \
      (0x1 << 4) \
      ),

  #define NBIO_IOMMU_L2_MEMORY_POWER_GATING_TBL \
    SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L2PWRGATING_ENABLED, \
      IOMMUL2x157000d4, \
      (0x1 << 0) | \
      (0x1 << 1) | \
      (0x1 << 2), \
      (0x1 << 0) | \
      (0x1 << 1) | \
      (0x1 << 2) \
      ), \
    SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L2PWRGATING_ENABLED, \
      IOMMUL2x13f01254, \
      (0x1 << 0) | \
      (0x1 << 1) | \
      (0x1 << 2), \
      (0x1 << 0) | \
      (0x1 << 1) | \
      (0x1 << 2) \
      ),

  #define NBIO_IOMMU_L1_MEMORY_POWER_GATING_TBL \
    SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L1PWRGATING_ENABLED, \
      IOMMUL1x147000e4, \
      (0x1 << 0) | \
      (0x1 << 1) | \
      (0x1 << 2) | \
      (0x1 << 3) , \
      (0x1 << 0) | \
      (0x1 << 1) | \
      (0x1 << 2) | \
      (0x1 << 3) \
      ), \
    SMN_ENTRY_PROPERTY_RMW(PROPERTY_IOMMU_L1PWRGATING_ENABLED, \
      IOMMUL1x148000e4, \
      (0x1 << 0) | \
      (0x1 << 1) | \
      (0x1 << 2) | \
      (0x1 << 3) , \
      (0x1 << 0) | \
      (0x1 << 1) | \
      (0x1 << 2) | \
      (0x1 << 3) \
      ),
