@echo off
Rem Batch file to generate the web visible SIL Code documentation file(s)
Rem   for use/display on the gh_pages web site.
Rem

Rem Validate that the project control files exist
if not exist "SilCode.dox"     ( Echo "GenPdf: ERROR missing Doxygen config file."       & cd .. & exit /b 1 )

Rem Make sure the build dir is present.
if not exist "build"  (
    mkdir build
) else (
    del /S /Q build\*.*  > nul
)

Rem Use Doxygen to parse the source tree; output to .\build\DoxyScans
echo " ************************************"
echo " Starting Doxygen scan for SilCode project"
doxygen SilCode.dox >> build\DoxyCons.log
if %ERRORLEVEL% NEQ 0 (
    echo "**** Dox: Doxygen generation failed."
    echo "****"
    goto Exit
)
if exist "build/Doxy.log" (
    echo "**** Dox: Warnings or Errors occurred! Check the build/Doxy.log file."
    echo "****"
)
echo " ************************************"
echo "Note The top HTML page generated by Doxygen is placed here: /docs/Code-html/"
echo " and is visible here: https://literate-broccoli-67e0cb61.pages.github.io/Code-html"

Rem return to the xDocs dir
:Exit
